name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: webpack
    - name: Run a multi-line script
      run: |
        echo hello world
        echo test, and deploy your project.
